# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 89799b19dd926b623667b5ef62b863bffac00550b2a764c2ee54f171164725c809f017a8beccf01396785682c859f59d0922fd9ac7c663db680ca0fe3c434829

test:
  secret_key_base: ca38caeab702ddde620d730ecb7853317dbb42e7476f8087a2def7da0b44430be19385284cdc3c767ec921bbcae9946a50985dc5deb0824592eaa6ea571b6fc3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
